name: clang-format-check

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Start container
      run: |
        docker run \
          -it --name CI_container \
          -v ${{ github.workspace }}:/Package \
          -v /cvmfs:/cvmfs:shared \
          -d clicdp/cc7-lcg96b /bin/bash
    - name: Check Format
      run: |
        docker exec CI_container /bin/bash -c "./Package/.github/scripts/clang_format_check.sh"
