name: clang-format-check

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Start container
      run: |
        docker run \
          -it --name k4MW_CI \
          -v ${{ github.workspace }}:/k4MW \
          -v /cvmfs:/cvmfs:shared \
          -d clicdp/cc7-lcg /bin/bash

    - name: Check Format
      run: |
        docker exec k4MW_CI /bin/bash -c 'source /cvmfs/sft.cern.ch/lcg/releases/clang/10.0.0-62e61/x86_64-centos7/setup.sh\
        clang-format -Werror --verbose --dry-run --style=file  $(find ./k4MW/ -name "*.cpp" -o -name "*.h" )\
        exit $?\
        '
