name: doctest-linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SETUP: ['/cvmfs/sw.hsf.org/key4hep/setup.sh', '/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh']
        PAGE: ['doc/starterkit/k4MarlinWrapperCLIC/Readme', ]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Start container
      run: |
        docker run -it --name CI_container -v ${GITHUB_WORKSPACE}:/Package -v /cvmfs:/cvmfs:shared -d clicdp/cc7-lcg /bin/bash
    - name: Setup container
      run: |
        docker exec CI_container /bin/bash -c ' ln -s /usr/lib64/liblzma.so.5.2.2 /usr/lib64/liblzma.so;\
        source ${{ matrix.SETUP }};\
        pip3 install jupytext;\
        pip3 install --upgrade jupyter;\
        python -m ipykernel install --name python3;\
        python -m ipykernel install --name bash;\
        '

    - name: Compile
      run: |
        docker exec CI_container /bin/bash -c ' cd Package;/
        source ${{ matrix.SETUP }};\
        mkdir build; cd build;\
        cmake .. ;\
        make -j 2;\
        '

    - name: CheckPage  
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;\
        source ${{ matrix.SETUP }};\
        source build/k4marlinwrapperenv.sh;\
        export PATH=$HOME/.local/bin/:$PATH;\
        cat .github/scripts/yamlheader.md  ${{ matrix.PAGE }}.md > ${{ matrix.PAGE }}-test.md;\
        testfilename=$(basename ${{ matrix.PAGE }}-test.md);\
        testdirname=$(dirname ${{ matrix.PAGE }}-test.md);\
        cd $testdirname;\
        jupytext $testfilename -o ${testfilename/-test.md/.ipynb} --execute;\
        '
