name: doctest-linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SETUP: ['/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh']
        PAGE: ['doc/starterkit/k4MarlinWrapperCLIC/Readme', ]
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - name: Start container
      run: |
        docker run -it --name CI_container -v ${GITHUB_WORKSPACE}:/Package -v /cvmfs:/cvmfs:shared -d ghcr.io/aidasoft/centos7:latest /bin/bash
    - name: Compile
      run: |
        docker exec CI_container /bin/bash -c ' cd Package;/
        source ${{ matrix.SETUP }};\
        mkdir build; cd build;\
        cmake .. ;\
        make -j 2;\
        '
    - name: CheckPage  
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;
        source ${{ matrix.SETUP }};
        source build/k4marlinwrapperenv.sh;
        mkdir testdir;
        cat .github/scripts/yamlheader.md  ${{ matrix.PAGE }}.md > testdir/test.md;
        cd testdir;
        jupytext test.md -o test.ipynb --execute;
        '
