name: doctest-linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SETUP: ['/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh']
        PAGE: ['doc/starterkit/k4MarlinWrapperCLIC/Readme',
               'doc/starterkit/k4MarlinWrapperCLIC/CEDViaWrapper']
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3.1
    - name: Start container
      run: |
        docker run -it --name CI_container -v ${GITHUB_WORKSPACE}:/Package -v /cvmfs:/cvmfs:shared -d ghcr.io/aidasoft/centos7:latest /bin/bash
    - name: Compile
      run: |
        docker exec CI_container /bin/bash -c ' cd Package;/
        source ${{ matrix.SETUP }};\
        mkdir build; cd build;\
        cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=../install;\
        ninja install;\
        '
    - name: CheckPage
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;
        source ${{ matrix.SETUP }};
        export LD_LIBRARY_PATH=/Package/install/lib64:$LD_LIBRARY_PATH
        export PYTHONPATH=/Package/install/python:$PYTHONPATH
        export K4MARLINWRAPPER=/Package/install/share/k4MarlinWrapper
        mkdir testdir;
        cat .github/scripts/yamlheader.md  ${{ matrix.PAGE }}.md > testdir/test.md;
        cd testdir;
        jupytext test.md -o test.ipynb --execute;
        '
